name: aging_genome
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.20.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - pysam>=0.16.0
  - cooler>=0.8.11
  - hicmatrix>=13
  - pybedtools>=0.8.0
  - pybigwig>=0.3.0
  - plotly>=5.0.0
  - bokeh>=2.3.0
  - scikit-learn>=1.0.0
  - statsmodels>=0.13.0
  - jupyter
  - jupyterlab
  - r-base>=4.1
  - r-essentials
  - bioconductor-genomicranges
  - bioconductor-rtracklayer
  - pip
  - pip:
    - scanpy>=1.8.0
    - anndata>=0.7.6 